## Basic Configuration

baseurl = "https://jerrychong.com"
builddrafts = true
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Jerry Chong"
title = "Jerry Chong"

theme = "goa"

## Hugo Built-in Features
#disqusShortname = "https-zanglang-github-io"
googleAnalytics = "G-L08PSNYVSF"
enableRobotsTXT = true

## Site Settings
[params]
author = "Jerry Chong"
intro = "DevOps Engineer @ NetbaseQuid, Taipei"
description = "Quintessential geek, caffeine addict, and avid technology enthusiast."
authorimage = "me.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Jerry Chong's profile"

## Social Accounts
[params.social]
github = "zanglang"
linkedin = "chongzhewei"
twitter = "zanglang"
telegram = "zanglang"
keybase = "zanglang"
email = "zanglang@gmail.com"
pgp = "8FEFAA9142CE1531069FA9C9654899A548A41038"

## Extras
[params.extra]
copyright = "[Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = false
socialmarkup = true
toc = false
displayrssicon = false

## Main Menu
#[[menu.main]]
#    name = "archives"
#    weight = 100
#    identifier = "blog"
#    url = "https://www.libcoffee.net"
#[[menu.main]]
#    name = "about"
#    identifier = "about"
#    weight = 200
#    url = "/about/"
